//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhanSu_DoAn2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LUONGNV
    {
        public string MaNV { get; set; }
        public string TenPhong { get; set; }
        public string HoTen { get; set; }
        public string MaLuong { get; set; }
        public Nullable<int> LCB { get; set; }
        public Nullable<int> PCChucVu { get; set; }
        public string Thuong { get; set; }
        public string KyLuat { get; set; }
        public string Thang { get; set; }
        public string Nam { get; set; }
        public Nullable<int> SoNgayCongThang { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<int> SoGioLamThem { get; set; }
        public Nullable<int> Luong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
    }
}
