//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhanSu_DoAn2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        public string MaBoPhan { get; set; }
        public string MaPhong { get; set; }
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string MaLuong { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string TTHonNhan { get; set; }
        public string CMTND { get; set; }
        public string NoiCap { get; set; }
        public string ChucVu { get; set; }
        public string LoaiHD { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string GhiChu { get; set; }
        public string MACTY { get; set; }
    
        public virtual tb_LUONGNV tb_LUONGNV { get; set; }
    }
}
